---
title: "Accuracy"
author: "Dana Lanceman"
date: "11/25/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'C:/Users/danal/OneDrive - UNSW/Desktop/WRL/R')
```


```{r get packages}
library(tidyverse)
library(ggpubr)
library(readxl)
```

```{r get data}
producers <- read_excel("raw/training_validation_matrix.xlsx", sheet = "producers") %>% 
  mutate(Scale = as.factor(Scale))
users <- read_excel("raw/training_validation_matrix.xlsx", sheet = "users")  %>% 
  mutate(Scale = as.factor(Scale))
```


```{r view in wide format and export for data table}
prod_wide <- producers %>% dplyr::select(Dataset, Scale, Class, Average) %>% pivot_wider(names_from = Class, values_from = Average)

#write_csv(prod_wide,"export/csv/producers_wide.csv")

user_wide <- users %>% dplyr::select(Dataset, Scale, Class, Average) %>% pivot_wider(names_from = Class, values_from = Average)

#write_csv(user_wide,"export/csv/users_wide.csv")
```


```{r functions}
acc.time.line <- function(dataset, classs, classname){
  dataset %>% subset(Class == classs)  %>% ggplot(aes(x = Date, y = Average*100, color = Scale)) +
  geom_line(size = 2) + 
geom_pointrange(aes(ymin=(Average-SD)*100, ymax=(Average+SD)*100), size = 2) + 
  labs(title = classname, x = "Date", y = "Accuracy (%)", color = "Resolution (m)") +
  theme_bw() +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 56),
        text = element_text(size = 44),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.margin = margin(10,22,10,10)) +
    geom_hline(yintercept = 80, linetype = "dashed", size = 3) +
    ylim(35, 100)
}


# delete this function
acc.scale <- function(dataset, datee, datename){
  dataset %>% subset(Dataset == datee, Class = c("spor", "sarc", "sueda"))  %>% ggplot(aes(x = Scale, y = Average*100, color = Class)) +
  geom_line(size = 2) + 
geom_pointrange(aes(ymin=(Average-SD)*100, ymax=(Average+SD)*100), size = 2) + 
  labs(title = datename, x = "Pixel size (m)", y = "Accuracy (%)") +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 56),
        text = element_text(size = 44),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
    ylim(35, 100)
}
```


# accuracy per class over time

```{r producer's accuracy}
spor <- acc.time.line(producers, "spor", "Sporobolus") +
  labs(title = "Sporobolus", x = "", y = "")
spor

sarc <- acc.time.line(producers, "sarc", "Sarcorcornia") +
  labs(title = "Sarcorcornia", x = "", y = "Accuracy (%)") 
sarc

grass <- acc.time.line(producers, "grass", "Grass") +
  labs(title = "Grass", x = "", y = "")
grass

mud <- acc.time.line(producers, "mud", "Mud")
mud

water <- acc.time.line(producers, "water", "Water")  +
  labs(title = "Water", x = "Date", y = "")
water

sueda <- acc.time.line(producers, "sueda", "Suaeda")  +
  labs(title = "Suaeda", x = "", y = "Accuracy (%)") +
  scale_x_datetime(date_labels = "%Y", date_breaks = "1 year")
sueda

dead <- acc.time.line(producers, "white_vege", "Dead vegetation")  +
  labs(title = "Dead vegetation", x = "", y = "Accuracy (%)") 
dead

road <- acc.time.line(producers, "road", "Road") +
  labs(title = "Road", x = "", y = "")
road 


# only one data point for each of these
acc.time.line(producers, "sarc_clump", "Sarcorcornia clumps")
acc.time.line(producers, "algae", "Algae") 


# combine
ggarrange(sarc, spor, sueda, grass, dead, road, mud, water, ncol = 2, nrow = 4, common.legend = TRUE, legend = "bottom") 
# export at 2100 x 2800

```



```{r user's accuracy}
spor <- acc.time.line(users, "spor", "Sporobolus") +
  labs(title = "Sporobolus", x = "", y = "")
spor

sarc <- acc.time.line(users, "sarc", "Sarcorcornia") +
  labs(title = "Sarcorcornia", x = "", y = "Accuracy (%)") 
sarc

grass <- acc.time.line(users, "grass", "Grass") +
  labs(title = "Grass", x = "", y = "")
grass

mud <- acc.time.line(users, "mud", "Mud")
mud

water <- acc.time.line(users, "water", "Water")  +
  labs(title = "Water", x = "Date", y = "")
water

sueda <- acc.time.line(users, "sueda", "Suaeda")  +
  labs(title = "Suaeda", x = "", y = "Accuracy (%)") +
  scale_x_datetime(date_labels = "%Y", date_breaks = "1 year")
sueda

dead <- acc.time.line(users, "white_vege", "Dead vegetation")  +
  labs(title = "Dead vegetation", x = "", y = "Accuracy (%)") 
dead

road <- acc.time.line(users, "road", "Road") +
  labs(title = "Road", x = "", y = "")
road 


# only one data point for each of these
acc.time.line(users, "sarc_clump", "Sarcorcornia clumps")
acc.time.line(users, "algae", "Algae") 



# combine
ggarrange(sarc, spor, sueda, grass, dead, road, mud, water, ncol = 2, nrow = 4, common.legend = TRUE, legend = "bottom") 
# export at 2100 x 2800
```


# accuracy per date by scale - delete this section


```{r producer's accuracy}
scale0 <- acc.scale(producers, "0mos", "0 months") +
  labs(title = "0 months", x = "", y = "Accuracy (%)")
scale0

scale9 <- acc.scale(producers, "9mos", "9 months") +
  labs(title = "9 months", x = "", y = "") 
scale9

scale21 <- acc.scale(producers, "21mos", "21 months") +
  labs(title = "21 months", x = "", y = "Accuracy (%)")
scale21

scale26 <- acc.scale(producers, "26mos", "26 months") +
  labs(title = "26 months", x = "", y = "")
scale26

scale34 <- acc.scale(producers, "34mos", "34 months")  +
  labs(title = "34 months", x = "", y = "Accuracy (%)")
scale34

scale42 <- acc.scale(producers, "42mos", "42 months")  +
  labs(title = "42 months", x = "Pixel size (m)", y = "") 
scale42

scale46 <- acc.scale(producers, "46mos", "46 months")  +
  labs(title = "46 months", x = "Pixel size (m)", y = "Accuracy (%)") 
scale46




# combine
ggarrange(scale0, scale9, scale21, scale26, scale34, scale42, scale46, ncol = 2, nrow = 4, common.legend = TRUE, legend = "bottom") + 
  theme(legend.title = element_blank())
# export at 2100 x 2800

# need to remove the legend title = attempt above didn't work
```

