---
title: "Class areas"
author: "Dana Lanceman"
date: "11/23/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/danal/OneDrive - UNSW/Desktop/WRL/R")
```

```{r load packages}
library(tidyverse)
library(raster)
library(sf)
library(gdata)
library(ggpubr)
library(viridis)

# note that both tidyverse and raster have functions "select" and "extract"
```

```{r load data}
# full data
zero1 <- raster("raw/0mos_classified_0_1_all.tif")
nine1 <- raster("raw/9mos_classified_01_all_new.tif")
eighteen1 <- raster("raw/18mos_classified_01_all.tif")
twentysix1 <- raster("raw/26mos_classified_01_all.tif")
thirtyfour1 <- raster("raw/34mos_classified_01_all.tif")
fortytwo1 <- raster("raw/42mos_classified_01_all.tif")
fortysix1 <- raster("raw/46mos_classified_01_all.tif")

# cropped maps
zero2 <- raster("raw/0mos_classified_crop.tif")
nine2 <- raster("raw/9mos_classified_crop.tif")
eighteen2 <- raster("raw/18mos_classified_crop.tif")
twentysix2 <- raster("raw/26mos_classified_crop.tif")
thirtyfour2 <- raster("raw/34mos_classified_crop.tif")
fortytwo2 <- raster("raw/42mos_classified_crop.tif")
fortysix2 <- raster("raw/46mos_classified_crop.tif")


# get shapefile and convert to same coordinate system
boundary <- st_read('raw/Clip_work.shp')
boundary <- st_transform(boundary, CRS(proj4string(zero1)))
```


```{r visualise data}
plot(zero1)
plot(nine1)
plot(eighteen1)
plot(twentysix1) # background is labelled # 5 - need to remove
plot(thirtyfour1)
plot(fortytwo1)
plot(fortysix1) # background is labelled # 5 - need to remove

plot(boundary)

plot(zero2)
plot(nine2)
plot(eighteen2)
plot(twentysix2)
plot(thirtyfour2)
plot(fortytwo2)
plot(fortysix2)
```

```{r crop out background for 26 mos and 46 mos}
# crop 26 mos
twsix1.crop <- crop(twentysix1, extent(boundary)) 
twsix1.crop <- mask(twsix1.crop, boundary)
plot(twsix1.crop)

# crop 46 mos
fosix1.crop <- crop(fortysix1, extent(boundary)) 
fosix1.crop <- mask(fosix1.crop, boundary)
plot(fosix1.crop)

```


```{r reassign sarc_clumps as sarc in 9 mos}
# reclassify class 8 as class 2

# create 2 column reclassification matrix for integer data
matrix.data <- c(0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,2)
matrix <- matrix(matrix.data, nrow = 9, ncol = 2, byrow = TRUE)
matrix

# use matrix for reclassifications
nine1 <- reclassify(nine1, matrix)
nine2 <- reclassify(nine2, matrix)

# visualise
plot(nine1)
plot(nine2)
```



```{r functions for creating saltmarsh row}
# with 3 saltmarsh classes
addsaltrow <- function(df, row1, row2, row3){
  rbind(df, data.frame(category = "saltmarsh", value = "na", df[row1, c(2,4)] + df[row2, c(2,4)] + df[row3, c(2,4)]))
}

# with 2 saltmarsh classes
add2saltrow <- function(df, row1, row2){
  rbind(df, data.frame(category = "saltmarsh", value = "na", df[row1, c(2,4)] + df[row2, c(2,4)]))
}
```


# Calculating areas - 0.1m resolution
```{r 0 mos}
# calculate number of cells in each class
cells0 <- freq(zero1) # output is vectors
cells0DF1 <- as.data.frame(cells0) # make this a dataframe
cells0DF1$category <- c("na", "spor","sarc", "grass", "mud", "water", "white_vege","road") # add categories
cells0DF1

# determine cell size in map units
res(zero1) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells0DF1$area <- cells0DF1$count*0.1*0.1/10000

cells0DF1 <- add2saltrow(cells0DF1,2,3)
cells0DF1
```


```{r 9 mos}
# 9 mos 
# calculate number of cells in each class
cells9 <- freq(nine1) # output is vectors
cells9DF1 <- as.data.frame(cells9) # make this a dataframe
cells9DF1$category <- c("na", "spor", "sarc",  "grass", "mud", "water", "white_vege", "road") # add categories
cells9DF1

# determine cell size in map units
res(nine1) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells9DF1$area <- cells9DF1$count*0.1*0.1/10000

cells9DF1 <- add2saltrow(cells9DF1,2,3)
cells9DF1
```


```{r 18 mos}
# 18 mos
# calculate number of cells in each class
cells18 <- freq(eighteen1) # output is vectors
cells18DF1 <- as.data.frame(cells18) # make this a dataframe
cells18DF1$category <- c("na", "spor","sarc", "grass", "mud", "water","sueda","road",  "white_vege") # add categories
cells18DF1

# determine cell size in map units
res(eighteen1) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells18DF1$area <- cells18DF1$count*0.1*0.1/10000

cells18DF1 <- addsaltrow(cells18DF1,2,3,7)
cells18DF1
```


```{r 26 mos}
# 26 mos 
# calculate number of cells in each class
cells26 <- freq(twsix1.crop) # output is vectors
cells26DF1 <- as.data.frame(cells26) # make this a dataframe
cells26DF1$category <- c("spor","sarc", "grass", "mud", "water","sueda", "road", "white_vege","na") # add categories
cells26DF1

# determine cell size in map units
res(twsix1.crop) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells26DF1$area <- cells26DF1$count*0.1*0.1/10000

cells26DF1 <- addsaltrow(cells26DF1,1,2,6)
cells26DF1
```


```{r 34 mos}
# 34 mos 
# calculate number of cells in each class
cells34 <- freq(thirtyfour1) # output is vectors
cells34DF1 <- as.data.frame(cells34) # make this a dataframe
cells34DF1$category <- c("na", "spor","sarc","grass", "mud", "water","sueda","road", "white_vege") # add categories
cells34DF1

# determine cell size in map units
res(thirtyfour1) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells34DF1$area <- cells34DF1$count*0.1*0.1/10000

cells34DF1 <- addsaltrow(cells34DF1,2,3,7)
cells34DF1
```


```{r 42 mos}
# 42 mos
# calculate number of cells in each class
cells42 <- freq(fortytwo1) # output is vectors
cells42DF1 <- as.data.frame(cells42) # make this a dataframe
cells42DF1$category <- c("na", "spor","sarc","grass", "mud", "water","algae","road", "white_vege", "sueda") # add categories
cells42DF1

# determine cell size in map units
res(fortytwo1) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells42DF1$area <- cells42DF1$count*0.1*0.1/10000

cells42DF1 <- addsaltrow(cells42DF1,2,3,10)
cells42DF1
```


```{r 46 mos}
# 46 mos 
# calculate number of cells in each class
cells46 <- freq(fosix1.crop) # output is vectors
cells46DF1 <- as.data.frame(cells46) # make this a dataframe
cells46DF1$category <- c("spor","sarc","grass", "mud", "water","sueda","road", "white_vege", "na") # add categories
cells46DF1

# determine cell size in map units
res(fosix1.crop) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells46DF1$area <- cells46DF1$count*0.1*0.1/10000

cells46DF1 <- addsaltrow(cells46DF1,1,2,6)
cells46DF1
```


# Combine datasets

```{r combine datasets}
one_scale <- combine(cells0DF1, cells9DF1, cells18DF1, cells26DF1, cells34DF1, cells42DF1, cells46DF1) %>% 
  subset(value != 0, value != "NA") #remove irrelevant values

# change source column to a date column
one_scale$source <- recode(one_scale$source,
         "cells0DF1" = "2017/02/03",
         "cells9DF1" = "2017/10/19",
         "cells18DF1" = "2018/11/09",
         "cells26DF1" = "2019/04/30",
         "cells34DF1" = "2019/12/18",
         "cells42DF1" = "2020/08/13",
         "cells46DF1" = "2020/12/08",) %>% as.Date() 
one_scale <- rename(one_scale, date = source) # rename source column to date
one_scale <- one_scale %>% mutate(Scale = 0.1) # add column for scale
  
one_scale
```


```{r plot}
# function
area.plot <- function(classs, classname){
  one_scale %>% subset(category == classs)  %>% ggplot(aes(x = date, y = area, color = as.factor(Scale))) +
  geom_line(size = 2) + 
  labs(title = classname, x = "Date", y = "Area (ha)") +
  theme_bw() +
  theme(legend.position = "none",
        plot.title = element_text(face = "bold", hjust = 0.5, size = 56),
        text = element_text(size = 44),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
}

spor.area <- area.plot("spor","Sporobolus")
sarc.area <- area.plot("sarc","Sarcorcornia")
sueda.area <- area.plot("sueda","Suaeda")
grass.area <- area.plot("grass","Grass")
mud.area <- area.plot("mud","Mud")
road.area <- area.plot("road","Road")
water.area <- area.plot("water","Water")
dead.area <- area.plot("white_vege","Dead vegetation")
salt.area <- area.plot("saltmarsh", "All saltmarsh")
spor.area 
sarc.area 
sueda.area 
grass.area 
mud.area 
road.area 
water.area 
dead.area
salt.area

# combine eight main plots
ggarrange(sarc.area, spor.area, sueda.area, grass.area, dead.area, road.area, mud.area, water.area, ncol = 2, nrow = 4, common.legend = TRUE, legend = "bottom") 
```

```{r plot together}
# function

combo_plot <- function(x){
  x %>% 
    filter(category %in% c("spor", "sarc", "sueda", "saltmarsh")) %>%  
  ggplot() +
    aes(x = date, y = area, color = category, linetype = category) +
  geom_line(size = 3) +
  scale_color_viridis(name = "Category", labels = c("All saltmarsh", "Sarcocornia", "Sporobolus", "Suaeda"), discrete = TRUE, option = "turbo") +
    scale_linetype_manual(name = "Category", labels = c("All saltmarsh", "Sarcocornia", "Sporobolus", "Suaeda"), values=c(1,2,3,4)) +
    labs(x = "Date", y = "Area (ha)", color = "Category", linetype = "Category") +
  theme_classic() +
  guides(color = guide_legend(byrow = TRUE)) + # for legend spacing 
  theme(axis.text = element_text(size = 40),
        axis.title = element_text(size = 54),
        legend.text = element_text(size = 30),
        legend.title = element_text(size = 36),
        plot.margin = margin(20,10,10,10),
        legend.spacing.y = unit(1, "cm"),
        legend.key.size = unit(3,"line"))
}

combo_plot(one_scale)

# export at 2100 x 1400
```

also add line for total saltmarsh area?





# Only target area


# Calculating areas - 0.1m resolution
```{r 0 mos}
# calculate number of cells in each class
cells01 <- freq(zero2) # output is vectors
cells0DF2 <- as.data.frame(cells01) # make this a dataframe
cells0DF2$category <- c("na", "spor","sarc", "grass", "mud", "water", "white_vege","road") # add categories
cells0DF2

# determine cell size in map units
res(zero2) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells0DF2$area <- cells0DF2$count*0.1*0.1/10000

cells0DF2 <- add2saltrow(cells0DF2,2,3)
cells0DF2
```


```{r 9 mos}
# 9 mos 
# calculate number of cells in each class
cells09 <- freq(nine2) # output is vectors
cells9DF2 <- as.data.frame(cells09) # make this a dataframe
cells9DF2$category <- c("na", "spor", "sarc",  "grass", "mud", "water", "white_vege", "road") # add categories
cells9DF2

# determine cell size in map units
res(nine2) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells9DF2$area <- cells9DF2$count*0.1*0.1/10000

cells9DF2 <- add2saltrow(cells9DF2,2,3)
cells9DF2
```


```{r 18 mos}
# 18 mos
# calculate number of cells in each class
cells018 <- freq(eighteen2) # output is vectors
cells18DF2 <- as.data.frame(cells018) # make this a dataframe
cells18DF2$category <- c("na", "spor","sarc", "grass", "mud", "water","sueda","road",  "white_vege") # add categories
cells18DF2

# determine cell size in map units
res(eighteen2) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells18DF2$area <- cells18DF2$count*0.1*0.1/10000

cells18DF2 <- addsaltrow(cells18DF2,2,3,7)
cells18DF2
```


```{r 26 mos}
# 26 mos 
# calculate number of cells in each class
cells026 <- freq(twentysix2) # output is vectors
cells26DF2 <- as.data.frame(cells026) # make this a dataframe
cells26DF2$category <- c("spor","sarc", "grass", "mud", "water","sueda", "road", "white_vege","na") # add categories
cells26DF2

# determine cell size in map units
res(twentysix2) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells26DF2$area <- cells26DF2$count*0.1*0.1/10000

cells26DF2 <- addsaltrow(cells26DF2,1,2,6)
cells26DF2
```


```{r 34 mos}
# 34 mos 
# calculate number of cells in each class
cells034 <- freq(thirtyfour2) # output is vectors
cells34DF2 <- as.data.frame(cells034) # make this a dataframe
cells34DF2$category <- c("na", "spor","sarc","grass", "mud", "water","sueda","road", "white_vege") # add categories
cells34DF2

# determine cell size in map units
res(thirtyfour2) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells34DF2$area <- cells34DF2$count*0.1*0.1/10000

cells34DF2 <- addsaltrow(cells34DF2,2,3,7)
cells34DF2
```


```{r 42 mos}
# 42 mos
# calculate number of cells in each class
cells042 <- freq(fortytwo2) # output is vectors
cells42DF2 <- as.data.frame(cells042) # make this a dataframe
cells42DF2$category <- c("na", "spor","sarc","grass", "mud", "water","algae","road", "white_vege", "sueda") # add categories
cells42DF2

# determine cell size in map units
res(fortytwo2) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells42DF2$area <- cells42DF2$count*0.1*0.1/10000

cells42DF2 <- addsaltrow(cells42DF2,2,3,10)
cells42DF2
```


```{r 46 mos}
# 46 mos 
# calculate number of cells in each class
cells046 <- freq(fortysix2) # output is vectors
cells46DF2 <- as.data.frame(cells046) # make this a dataframe
cells46DF2$category <- c("spor","sarc","grass", "mud", "water","sueda","road", "white_vege", "na") # add categories
cells46DF2

# determine cell size in map units
res(fortysix2) # cell size is 0.1 x 0.1 (metres)

# use this to calculate area of each class in hectares
cells46DF2$area <- cells46DF2$count*0.1*0.1/10000

cells46DF2 <- addsaltrow(cells46DF2,1,2,6)
cells46DF2
```


# Combine datasets

```{r combine datasets}
one_scale2 <- combine(cells0DF2, cells9DF2, cells18DF2, cells26DF2, cells34DF2, cells42DF2, cells46DF2) %>% 
  subset(value != 0, value != "NA") #remove irrelevant values

# change source column to a date column
one_scale2$source <- recode(one_scale2$source,
         "cells0DF2" = "2017/02/03",
         "cells9DF2" = "2017/10/19",
         "cells18DF2" = "2018/11/09",
         "cells26DF2" = "2019/04/30",
         "cells34DF2" = "2019/12/18",
         "cells42DF2" = "2020/08/13",
         "cells46DF2" = "2020/12/08",) %>% as.Date() 
one_scale2 <- rename(one_scale2, date = source) # rename source column to date
one_scale2 <- one_scale2 %>% mutate(Scale = 0.1) # add column for scale
  
one_scale2
```


```{r plot}
combo_plot(one_scale2)
# 2100 x 1400
```


