---
title: "patch_metrics"
author: "Dana Lanceman"
date: "12/8/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'C:/Users/danal/OneDrive - UNSW/Desktop/WRL/R')
```

```{r get packages}
library(tidyverse)
library(raster)
library(sf)
install.packages('Rcpp')
library(Rcpp)
library(landscapemetrics)
```


```{r load data - just 0.1 resolution}
zero1 <- raster("raw/0mos_classified_0_1_proper.tif")
nine1 <- raster("raw/9mos_classified_8class_0_1.tif")
eighteen1 <- raster("raw/18mos_classified_0_1_allclass.tif")
twentysix1 <- raster("raw/26mos_classified_0_1_allclass.tif")
thirtyfour1 <- raster("raw/34mos_classified_0_1_proper.tif")
fortytwo1 <- raster("raw/42mos_classified_0_1_proper.tif")
fortysix1 <- raster("raw/46mos_classified_0_1_proper.tif")

# get shapefile and convert to same coordinate system
# need to replace the #'s with a real file name
boundary <- st_read('raw/Clip_work.shp')
boundary <- st_transform(boundary, CRS(proj4string(zero)))
```


```{r visualise data}
plot(zero1)
plot(nine1)
plot(eighteen1)
plot(twentysix1) # background is labelled # 5 - need to remove
plot(thirtyfour1)
plot(fortytwo1)
plot(fortysix1) # background is labelled # 5 - need to remove

plot(boundary)
```

```{r crop out background for 26 mos and 46 mos}
# crop 26 mos
twsix1.crop <- crop(twentysix1, extent(boundary)) 
twsix1.crop <- mask(twsix1.crop, boundary)
plot(twsix1.crop)

# crop 46 mos
fosix1.crop <- crop(fortysix1, extent(boundary)) 
fosix1.crop <- mask(fosix1.crop, boundary)
plot(fosix1.crop)
```

Landscape metrics package
- article explaining: https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.04617
- documentation: https://cran.r-project.org/web/packages/landscapemetrics/landscapemetrics.pdf
```{r check data are suitable for landscapemetrics}
check_landscape(zero1)
check_landscape(nine1)
check_landscape(eighteen1)
check_landscape(twsix1.crop)
check_landscape(thirtyfour1)
check_landscape(fortytwo1)
check_landscape(fosix1.crop)
# all ok
```

```{r}
possible_metrics <- list_lsm() # list of all possible metrics
view(possible_metrics)

# calculate multiple metrics at once
calculate_lsm()
# either specify parameters for the types of metrics to calculate, or put a vector list metrics to calculate
```

```{r metrics for zero months}
# make a list of rasters
raster_names <- list(zero1, nine1, eighteen1, twentysix1, thirtyfour1, fortytwo1, fortysix1)

# make a function to add dataset names and categories to data
add.metadata <- function(x){
  x %>% mutate(
  dataset = case_when(id == 1 ~ "zero",
                                id == 2 ~ "nine",
                                id == 3 ~ "eighteen",
                                id == 4 ~ "twentysix",
                                id == 5 ~ "thirtyfour",
                                id == 6 ~ "fortytwo",
                                id == 7 ~ "fortysix"),
  category = c("na", "spor","sarc", "grass", "mud", "water", "white_vege","road", 
               "na", "spor", "sarc", "grass", "mud", "water", "white_vege", "sarc_clumps","road", 
               "na", "spor","sarc", "grass", "mud", "water","sueda","road",  "white_vege",
               "spor","sarc", "grass", "mud", "water","sueda", "white_vege","road", "na",
               "na", "spor","sarc","grass", "mud", "water","sueda","road", "white_vege",
               "na", "spor","sarc","grass", "mud", "water","algae","road", "white_vege", "sueda",
               "spor","sarc","grass", "mud", "water","sueda","road", "white_vege", "na"))
}


# apply functions

# CALCULATE CLASS METRICS

# area and edge metrics
area.means <- lapply(raster_names, lsm_c_area_mn) %>% bind_rows(.id = "id") %>% add.metadata() # patch area, mean
area.sds <- lapply(raster_names, lsm_c_area_sd) %>% bind_rows(.id = "id") %>% add.metadata() # patch area, sd
area.totals <- lapply(raster_names, lsm_c_ca) %>% bind_rows(.id = "id") %>% add.metadata() # total class area

# core area metrics
cai.mns <- lapply(raster_names, lsm_c_cai_mn) %>% bind_rows(.id = "id") %>% add.metadata() # core area index, mean
cai.sds <- lapply(raster_names, lsm_c_cai_sd) %>% bind_rows(.id = "id") %>% add.metadata() # core area index, sd
core.mns <- lapply(raster_names, lsm_c_core_mn) %>% bind_rows(.id = "id") %>% add.metadata() # alternative core area, mean
core.sds <- lapply(raster_names, lsm_c_core_sd) %>% bind_rows(.id = "id") %>% add.metadata() # alternative core area, sd

# aggregation metrics
nps <- lapply(raster_names, lsm_c_np) %>% bind_rows(.id = "id") %>% add.metadata() # number of patches
cohesions <- lapply(raster_names, lsm_c_cohesion) %>% bind_rows(.id = "id") %>% add.metadata() # cohesion
enn.mns <- lapply(raster_names, lsm_c_enn_mn) %>% bind_rows(.id = "id") %>% add.metadata() # euclidean nearest neighbour distance, mean
enn.sds <- lapply(raster_names, lsm_c_enn_sd) %>% bind_rows(.id = "id") %>% add.metadata() # euclidean nearest neighbour distance, sd
clumpys <- lapply(raster_names, lsm_c_clumpy) %>% bind_rows(.id = "id") %>% add.metadata() # clumpiness

# shape metrics
contig.mns <- lapply(raster_names, lsm_c_contig_mn) %>% bind_rows(.id = "id") %>% add.metadata() # contiguity, mean
contig.sds <- lapply(raster_names, lsm_c_contig_sd) %>% bind_rows(.id = "id") %>% add.metadata() # contiguity, sd
shape.mns <- lapply(raster_names, lsm_c_shape_mn) %>% bind_rows(.id = "id") %>% add.metadata() # shape index, mean
shape.sds <- lapply(raster_names, lsm_c_shape_sd) %>% bind_rows(.id = "id") %>% add.metadata() # shape index, sd

# LANDSCAPE METRICS
# aggregation metrics
contags <- lapply(raster_names, lsm_l_contag) %>% bind_rows(.id = "id") %>% add.metadata() # contagion

# diversity metrics
shan.divs <- lapply(raster_names, lsm_l_shdi) %>% bind_rows(.id = "id") %>% add.metadata() # shannon diversity
shan.evens <- lapply(raster_names, lsm_l_shei) %>% bind_rows(.id = "id") %>% add.metadata() # shannon evenness 






# make this into a function
patch_metrics <- function(input, output){
  # CALCULATE CLASS METRICS
  # area and edge metrics
  area.mn <- lsm_c_area_mn(input) # patch area, mean
  area.sd <- lsm_c_area_sd(input) # patch area, sd
  area.total <- lsm_c_ca(input) # total class area
  # core area metrics
  core.mn <- lsm_c_cai_mn(input) # core area, mean - decide which of the two core area     metrics to use
  core.sd <- lsm_c_cai_sd(input) # core area, sd
  core2.mn <- lsm_c_core_mn(input) # core area, mean
  core2.sd <- lsm_c_core_sd(input) # core area, sd
  # aggregation metrics
  np <- lsm_c_np(input) # number of patches
  cohesion <- lsm_c_cohesion(input) # cohesion
  enn.mn <- lsm_c_enn_mn(input) # euclidean nearest neighbour distance, mean
  enn.sd <- lsm_c_enn_sd(input) # euclidean nearest neighbour distance, sd
  clumpy <- lsm_c_clumpy(input) # clumpiness
  # shape metrics
  contig.mn <- lsm_c_contig_mn(input) # contiguity, mean
  contig.sd <- lsm_c_contig_sd(input) # contiguity, sd
  shape.mn <- lsm_c_shape_mn(input) # shape index, mean
  shape.sd <- lsm_c_shape_sd(input) # shape index, sd
  # CALCULATE LANDSCAPE METRICS
  # aggregation metrics
  contag <- lsm_l_contag(input) # contagion
  # diversity metrics
  shan.div <- lsm_l_shdi(input) # shannon's diversity
  shan.even <- lsm_l_shei(input) # shannon's evenness
  
  output <- rbind(area.mn, area.sd, area.total, core.mn, core.sd, core2.mn, core2.sd, np, cohesion, enn.mn, enn.sd, clumpy, contig.mn, contig.sd, shape.mn, shape.sd, contag, shan.div, shan.even) # bind all outputs into one tibble
}
# note this function takes over 20 mins to run 



# add class names to each dataset
# 0 mos "na", "spor","sarc", "grass", "mud", "water", "white_vege","road"
zero_patches <- zero_patches %>% 
  mutate(category = case_when(class == 0 ~ "na", 
                              class == 1 ~ "spor",
                              class == 2 ~ "sarc",
                              class == 3 ~ "grass",
                              class == 4 ~ "mud",
                              class == 5 ~ "water",
                              class == 6 ~ "white_vege",
                              class == 7 ~ "road"))

# 9 mos "na", "spor", "sarc", "grass", "mud", "water", "white_vege", "sarc_clumps","road"
nine_patches <- nine_patches %>% 
  mutate(category = case_when(class == 0 ~ "na", 
                              class == 1 ~ "spor",
                              class == 2 ~ "sarc",
                              class == 3 ~ "grass",
                              class == 4 ~ "mud",
                              class == 5 ~ "water",
                              class == 6 ~ "white_vege",
                              class == 7 ~ "sarc_clumps",
                              class == 8 ~ "road"))

# 18 mos "na", "spor","sarc", "grass", "mud", "water","sueda","road",  "white_vege"


# 26 mos "spor","sarc", "grass", "mud", "water","sueda", "white_vege","road", "na"
# dont think this has class 0, NA at end instead?


# 34 mos "na", "spor","sarc","grass", "mud", "water","sueda","road", "white_vege"


# 42mos "na", "spor","sarc","grass", "mud", "water","algae","road", "white_vege", "sueda"

# 46 mos "spor","sarc","grass", "mud", "water","sueda","road", "white_vege", "na"
# dont think this has class 0, NA at end instead?


# then bind the diff datasets together
allpatch <- rbind(zero_patches, nine_patches, eighteen_patches, twentysix_patches, thirtyfour_patches, fortytwo_patches, fortysix_patches)

# then change to wide format with each patch metric as its own column
allpatch.w <- allpatch %>% dplyr::select(Dataset, Scale, Class, Average) %>% pivot_wider(names_from = Class, values_from = Average)



# CLASS METRICS
# area and edge metrics
area.mn <- lsm_c_area_mn(zero1) # patch area, mean
area.sd <- lsm_c_area_sd(zero1) # patch area, sd
area.total <- lsm_c_ca(zero1) # total class area
# core area metrics
core.mn <- lsm_c_cai_mn(zero1) # core area, mean - decide which of the two core area metrics to use
core.sd <- lsm_c_cai_sd(zero1) # core area, sd
core2.mn <- lsm_c_core_mn(zero1) # core area, mean
core2.sd <- lsm_c_core_sd(zero1) # core area, sd
# aggregation metrics
np <- lsm_c_np(zero1) # number of patches
cohesion <- lsm_c_cohesion(zero1) # cohesion
enn.mn <- lsm_c_enn_mn(zero1) # euclidean nearest neighbour distance, mean
enn.sd <- lsm_c_enn_sd(zero1) # euclidean nearest neighbour distance, sd
clumpy <- lsm_c_clumpy(zero1) # clumpiness
# shape metrics
contig.mn <- lsm_c_contig_mn(zero1) # contiguity, mean
contig.sd <- lsm_c_contig_sd(zero1) # contiguity, sd
shape.mn <- lsm_c_shape_mn(zero1) # shape index, mean
shape.sd <- lsm_c_shape_sd(zero1) # shape index, sd
# LANDSCAPE METRICS
# aggregation metrics
contag <- lsm_l_contag(zero1) # contagion
# diversity metrics
shan.div <- lsm_l_shdi(zero1) # shannon's diversity
shan.even <- lsm_l_shei(zero1) # shannon's evenness


zero_patches <- rbind(area.mn, area.sd, area.total, core.mn, core.sd, core2.mn, core2.sd, np, cohesion, enn.mn, enn.sd, clumpy, contig.mn, contig.sd, shape.mn, shape.sd, contag, shan.div, shan.even)
```


```{r}
# combine outputs
rbind(lsm_p_area(x), lsm_l_ai(x))
```

